import { vendorHeader } from '../install/vendor.js';
import type { ColorProposal } from './derive.js';

const TOP_COMMENT_FIRST_LINE = 'brand.default.css — unbranded default.';
const TOP_COMMENT_LAST_LINE = 'Copy to brand.<client>.css and override. Never edit this file per project.';

function round(n: number): number {
  return Math.round(n);
}

/**
 * Builds `brand.<project>.css` from a copy of the vendored
 * `tokens/brand.default.css`, replacing only:
 *   - the top usage note (this file is no longer "the unbranded default" —
 *     it names where its colour came from instead)
 *   - the `--brand-h` / `--brand-s` / `--brand-l` values
 *
 * The `================= BRAND =================` contract comment — the
 * 4.5:1-against-two-backgrounds requirement and the E-64 warning — is left
 * completely untouched, so the file keeps documenting the exact contract
 * `init` validated the proposed colour against.
 */
export function renderBrandFile(defaultCssRaw: string, projectSlug: string, version: string, proposal: ColorProposal): string {
  const fileName = `brand.${projectSlug}.css`;
  const header = vendorHeader(fileName, version, 'css');

  if (!defaultCssRaw.includes(TOP_COMMENT_FIRST_LINE) || !defaultCssRaw.includes(TOP_COMMENT_LAST_LINE)) {
    throw new Error(
      `brand-file: tokens/brand.default.css does not match the expected shape — ${TOP_COMMENT_FIRST_LINE} / ${TOP_COMMENT_LAST_LINE} not found.`,
    );
  }

  let body = defaultCssRaw.replace(
    TOP_COMMENT_FIRST_LINE,
    `${fileName} — generated by \`jig init\`.`,
  );
  body = body.replace(
    TOP_COMMENT_LAST_LINE,
    `Brand colour derived from: ${proposal.detail} (${proposal.source}). ` +
      "Edit --brand-h/-s/-l below directly — `jig update` will not touch this file.",
  );

  body = body.replace(/--brand-h:\s*[\d.]+;/, `--brand-h: ${round(proposal.h)};`);
  body = body.replace(/--brand-s:\s*[\d.]+%;/, `--brand-s: ${round(proposal.s)}%;`);
  body = body.replace(/--brand-l:\s*[\d.]+%;/, `--brand-l: ${round(proposal.l)}%;`);

  return header + body;
}

export function brandFileName(projectSlug: string): string {
  return `brand.${projectSlug}.css`;
}
